language: python
sudo: false
python: 3.7
env:
    - TOX_ENV=py37
    - TOX_ENV=py36
    - TOX_ENV=flake8
matrix:
    allow_failures:
        - env: TOX_ENV=py34
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
